export const POSTS_ENABLE_LOADER = 'POSTS_ENABLE_LOADER';
export const POSTS_DISABLE_LOADER = 'POSTS_DISABLE_LOADER';

// login
export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_RESPONSE = 'POSTS_RESPONSE';
export const POSTS_FAILED = 'POSTS_FAILED';
export const POSTS_LOADING_ENDED = 'POSTS_LOADING_ENDED';
